### ISSUE TITLE
Status: NotSupported/Failed to load assembly

### ISSUE THREAD

**Issue by LeviSnoot** [dkanada/jellyfin-plugin-intros#53]
So I just updated the plugin and it's unable to start, giving me the following error in the logs:

```
[2022-09-14 11:15:18.852 +02:00] [ERR] [1] Emby.Server.Implementations.Plugins.PluginManager: Failed to load assembly "D:\Jellyfin\Server\plugins\Intros_1.3.2.0\Jellyfin.Plugin.Intros.dll". This error occurs when a plugin references an incompatible version of one of the shared libraries. Disabling plugin.
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Could not load file or assembly 'MediaBrowser.Controller, Version=10.8.4.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
Could not load file or assembly 'MediaBrowser.Common, Version=10.8.4.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
Could not load file or assembly 'MediaBrowser.Model, Version=10.8.4.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
Could not load file or assembly 'MediaBrowser.Controller, Version=10.8.4.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
Could not load file or assembly 'MediaBrowser.Model, Version=10.8.4.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at Emby.Server.Implementations.Plugins.PluginManager.LoadAssemblies()+MoveNext()
System.IO.FileNotFoundException: Could not load file or assembly 'MediaBrowser.Controller, Version=10.8.4.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'MediaBrowser.Controller, Version=10.8.4.0, Culture=neutral, PublicKeyToken=null'
System.IO.FileNotFoundException: Could not load file or assembly 'MediaBrowser.Common, Version=10.8.4.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'MediaBrowser.Common, Version=10.8.4.0, Culture=neutral, PublicKeyToken=null'
System.IO.FileNotFoundException: Could not load file or assembly 'MediaBrowser.Model, Version=10.8.4.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'MediaBrowser.Model, Version=10.8.4.0, Culture=neutral, PublicKeyToken=null'
System.IO.FileNotFoundException: Could not load file or assembly 'MediaBrowser.Controller, Version=10.8.4.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'MediaBrowser.Controller, Version=10.8.4.0, Culture=neutral, PublicKeyToken=null'
System.IO.FileNotFoundException: Could not load file or assembly 'MediaBrowser.Model, Version=10.8.4.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'MediaBrowser.Model, Version=10.8.4.0, Culture=neutral, PublicKeyToken=null'
```

OS: Windows 11
Jellyfin version: 10.8.3

**Comment by LeviSnoot** [comment]
Closing as updating Jellyfin to 10.8.4 fixed the issue, some version mismatch somewhere caused this most likely.
